# src/plots.py
import json
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import (precision_score, recall_score, f1_score, roc_auc_score)
from src.config import REPORTS_DIR, FIGURES_DIR, ANOMALY_THRESHOLD

def generate_report():
    """Calculates strict metrics and generates the Anomaly Score Distribution plot."""
    print("Generating report and visualizations...")
    
    # Load the output generated by predict.py
    with open(REPORTS_DIR / 'evaluation_metrics.json', 'r') as f:
        results = json.load(f)

    # Extract lists of true labels and model predicted scores
    y_true = np.array([r['true_label'] for r in results])
    y_score = np.array([r['anomaly_score'] for r in results])
    
    # Convert floating scores to binary 0/1 predictions using the threshold (e.g. 0.5)
    y_pred = (y_score >= ANOMALY_THRESHOLD).astype(int)

    # --------------------------------------------------------
    # 1. Print Standard ML Metrics
    # --------------------------------------------------------
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec  = recall_score(y_true, y_pred, zero_division=0)
    f1   = f1_score(y_true, y_pred, zero_division=0)
    roc  = roc_auc_score(y_true, y_score)

    print("="*40)
    print("FINAL BENCHMARK RESULTS")
    print("="*40)
    print(f"Precision : {prec*100:.2f}% (How many flagged were actual anomalies?)")
    print(f"Recall    : {rec*100:.2f}% (How many total anomalies did we catch?)")
    print(f"F1-Score  : {f1:.4f}")
    print(f"ROC-AUC   : {roc:.4f}")
    print("="*40)

    # --------------------------------------------------------
    # 2. VISUALIZATION: Anomaly Score Distribution
    # (This is the specific snippet you requested)
    # --------------------------------------------------------
    # Separate the scores based on their TRUE label
    normal_scores = [r['anomaly_score'] for r in results if r['true_label'] == 0]
    anomaly_scores = [r['anomaly_score'] for r in results if r['true_label'] == 1]

    # Create the Matplotlib figure
    fig, ax = plt.subplots(figsize=(10, 6))

    # Plot Green histogram for Normal sessions
    ax.hist(normal_scores, bins=30, alpha=0.6, color='#4CAF50',
            label=f'Normal (n={len(normal_scores)})', density=True)
            
    # Plot Red histogram for Anomalous sessions
    ax.hist(anomaly_scores, bins=30, alpha=0.6, color='#F44336',
            label=f'Anomaly (n={len(anomaly_scores)})', density=True)

    # Plot aesthetics and labels
    ax.set_xlabel('Anomaly Score (fraction of anomalous windows)', fontsize=12)
    ax.set_ylabel('Density', fontsize=12)
    ax.set_title('Anomaly Score Distribution', fontsize=14, fontweight='bold')
    ax.legend(fontsize=11)
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    
    # Save the plot to the figures directory
    plot_path = FIGURES_DIR / 'anomaly_score_distribution.png'
    plt.savefig(plot_path, dpi=150)
    print(f"\nSaved distribution plot to {plot_path}")
    
    # Show it live if running in an interactive window
    plt.show()

if __name__ == "__main__":
    generate_report()